# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b0JX6IJ1jqBYmYzez5Te0FVMNL7u2QCF
"""

numbers=[12,45,23,45,67,12]

largest=float('-inf')
second_largest=float('-inf')

for num in numbers:
    if num > largest:
      second_largest=largest
      largest=num
    elif largest > num > second_largest:
      second_largest = num
if second_largest == float('-inf'):
    print("No second largest element exist")
else:
    print("Second largest unique element is:" ,second_largest)

numbers = [11,20,14,11,20,18,15]
frequency = {}
for num in numbers:
  if num in frequency:
    frequency[num] += 1
  else:
    frequency[num] = 1
for key, value in frequency.items():
    print(key, ":" ,value)